
services:
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - p-net
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db_name -U user_name"]
      interval: 1s
      timeout: 5s
      retries: 20
  backend:
    container_name: backend
    image: backend
    build: './backend/.'
    init: true
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - p-net
    ports:
      - 8001:8000
    volumes:
      - ./django-files/backend:/var/django-site

networks:
  p-net:
    driver: bridge
