# Generated by Django 5.0.3 on 2024-05-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/defaultAvatar.png', upload_to='avatar/'),
        ),
    ]
