# Generated by Django 5.0.3 on 2024-05-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpong', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pongstats',
            name='playerName',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
